# Use the official PostgreSQL 13 image as the base
FROM postgres:11

# Set environment variables (optional)
#Will set these in docker-compose

# Expose the PostgreSQL port
EXPOSE 5432

# Add initialization scripts (optional)
# COPY ./init.sql /docker-entrypoint-initdb.d/